class Message {
    constructor(senderID, recipientID, messageContents = "") {
        this.messageID = null; // Will be generated by the database
        this.senderID = senderID;
        this.recipientID = recipientID;
        this.messageContents = messageContents;
    }

    // Getters and Setters
    getMessageID() {
        return this.messageID;
    }

    setMessageID(messageID) {
        this.messageID = messageID;
    }

    getSenderID() {
        return this.senderID;
    }

    setSenderID(senderID) {
        this.senderID = senderID;
    }

    getRecipientID() {
        return this.recipientID;
    }

    setRecipientID(recipientID) {
        this.recipientID = recipientID;
    }

    getMessageContents() {
        return this.messageContents;
    }

    setMessageContents(messageContents) {
        this.messageContents = messageContents;
    }
}

module.exports = Message;
